(function(){
const API='https://fabrizio-romanio-backend.onrender.com';
const esc=v=>String(v??'').replace(/[&<>\"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',"'":'&#39;'}[c]));
function style(){if(document.getElementById('aiNewsStyles'))return;const s=document.createElement('style');s.id='aiNewsStyles';s.textContent=`.ai-news-panel{margin:42px 0 10px;border-radius:22px;overflow:hidden;background:#0b0c10;color:#fff;box-shadow:0 24px 70px rgba(0,0,0,.16)}.ai-news-head{padding:30px 34px;border-bottom:1px solid rgba(255,255,255,.09);display:flex;align-items:center;justify-content:space-between;gap:20px}.ai-news-kicker{font-size:10px;letter-spacing:.18em;font-weight:900;color:#ff4852}.ai-news-head h2{margin:6px 0 0;font-size:clamp(28px,4vw,46px);letter-spacing:-.05em;line-height:1}.ai-news-badge{border:1px solid rgba(255,255,255,.16);border-radius:999px;padding:9px 13px;font-size:11px;color:#bfc2ca;white-space:nowrap}.ai-news-body{padding:34px}.ai-news-loading{min-height:180px;display:grid;place-items:center;color:#aaa}.ai-news-error{padding:28px;border:1px solid rgba(255,255,255,.1);border-radius:14px;color:#ffb0b5;background:rgba(227,6,19,.07)}.ai-news-content{font-size:16px;line-height:1.82;color:#e4e5e9}.ai-news-content h2,.ai-news-content h3{color:#fff;line-height:1.2;margin:30px 0 10px}.ai-news-content h2{font-size:25px}.ai-news-content h3{font-size:19px}.ai-news-content p{margin:0 0 18px}.ai-news-content ul{margin:8px 0 20px;padding-left:22px}.ai-news-content li{margin:8px 0}.ai-news-sources{border-top:1px solid rgba(255,255,255,.1);margin-top:30px;padding-top:24px}.ai-news-sources strong{font-size:11px;letter-spacing:.12em;color:#ff4852}.ai-news-sources a{display:block;color:#c9ccd4;margin-top:9px;font-size:12px;text-decoration:underline;text-underline-offset:3px}.ai-news-refresh{border:0;background:#e30613;color:#fff;border-radius:10px;padding:11px 15px;font-weight:800;cursor:pointer}.ai-news-refresh:disabled{opacity:.5;cursor:wait}@media(max-width:650px){.ai-news-head{padding:24px;align-items:flex-start;flex-direction:column}.ai-news-body{padding:24px}.ai-news-badge{white-space:normal}}`;document.head.appendChild(s)}
function markdown(text){let x=esc(text);x=x.replace(/^### (.+)$/gm,'<h3>$1</h3>').replace(/^## (.+)$/gm,'<h2>$1</h2>').replace(/^# (.+)$/gm,'<h2>$1</h2>');x=x.replace(/^[-*] (.+)$/gm,'<li>$1</li>');x=x.replace(/(<li>.*<\/li>)(?:\n|$)/g,'<ul>$1</ul>');x=x.replace(/\*\*(.+?)\*\*/g,'<strong>$1</strong>');x=x.split(/\n\s*\n/).map(p=>/^<h[23]>|^<ul>/.test(p.trim())?p:`<p>${p.replace(/\n/g,'<br>')}</p>`).join('');return x}
async function run(v,type){const panel=document.getElementById('aiNewsPanel');if(!panel)return;const button=panel.querySelector('.ai-news-refresh');button.disabled=true;panel.querySelector('.ai-news-body').innerHTML='<div class="ai-news-loading">🤖 Gemini is researching this story and building a detailed briefing…</div>';try{const r=await fetch(API+'/api/ai/news-analysis',{method:'POST',headers:{'Content-Type':'application/json','Accept':'application/json'},body:JSON.stringify({title:v.title,description:v.description,channel:v.channel_title,published_at:v.published_at,url:v.url,type:type+' feature'})});const d=await r.json();if(!r.ok)throw new Error(d.message||d.error||'AI analysis failed');const sources=(d.sources||[]).map(s=>`<a href="${esc(s.url)}" target="_blank" rel="noopener noreferrer">${esc(s.title||s.url)}</a>`).join('');panel.querySelector('.ai-news-body').innerHTML=`<div class="ai-news-content">${markdown(d.analysis)}</div>${sources?`<div class="ai-news-sources"><strong>RESEARCH SOURCES</strong>${sources}</div>`:''}`;panel.dataset.loaded='1'}catch(e){panel.querySelector('.ai-news-body').innerHTML=`<div class="ai-news-error"><strong>AI research is unavailable right now.</strong><p>${esc(e.message)}</p><p>Add <code>GEMINI_API_KEY</code> to the backend environment and redeploy.</p></div>`}finally{button.disabled=false}}
function mount(v,type){style();if(document.getElementById('aiNewsPanel'))return;const article=document.querySelector('[data-feature-detail]');if(!article)return;const panel=document.createElement('section');panel.id='aiNewsPanel';panel.className='ai-news-panel';panel.innerHTML='<div class="ai-news-head"><div><div class="ai-news-kicker">GEMINI FOOTBALL INTELLIGENCE</div><h2>AI Deep News Analysis</h2></div><div><span class="ai-news-badge">Live web research</span></div></div><div class="ai-news-body"><div class="ai-news-loading">Preparing the story for AI research…</div></div>';article.insertAdjacentElement('afterend',panel);const head=panel.querySelector('.ai-news-head');const refresh=document.createElement('button');refresh.className='ai-news-refresh';refresh.textContent='Research again';head.appendChild(refresh);refresh.addEventListener('click',()=>run(v,type));run(v,type)}
async function init(){const params=new URLSearchParams(location.search),id=params.get('id'),type=params.get('type')||'transfer';if(!id)return;try{const query=type==='player'?'football player transfer news':type==='club'?'football club transfer news':'football transfer news';const r=await fetch(API+'/api/youtube-videos?limit=50&q='+encodeURIComponent(query));const d=await r.json();const videos=d.videos||[];const v=videos.find(x=>String(x.id)===String(id));if(v)mount(v,type)}catch(e){console.warn('AI feature setup failed',e)}}
document.addEventListener('DOMContentLoaded',init);
})();
