const MOVIE_API='https://fabrizio-romanio-backend.onrender.com';
const $=s=>document.querySelector(s);const esc=v=>String(v??'').replace(/[&<>\"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',"'":'&#39;'}[c]));
const REGIONS=[['NG','Nigeria'],['US','United States'],['GB','United Kingdom'],['CA','Canada'],['AU','Australia']];const getRegion=()=>localStorage.getItem('movieRegion')||'NG';const setRegion=r=>localStorage.setItem('movieRegion',r);
async function api(path){try{const r=await fetch(MOVIE_API+path,{headers:{Accept:'application/json'}});if(!r.ok)throw new Error('API '+r.status);return await r.json()}catch(e){console.warn(e);return null}}
function initNav(){const b=$('.menu-btn'),n=$('.nav-links');if(!b||!n)return;b.addEventListener('click',()=>n.classList.toggle('mobile-open'));n.querySelectorAll('a').forEach(a=>a.addEventListener('click',()=>n.classList.remove('mobile-open')))}
function regionControl(){return `<label class="region-control"><span>Availability</span><select class="movieRegion">${REGIONS.map(([code,name])=>`<option value="${code}" ${code===getRegion()?'selected':''}>${name}</option>`).join('')}</select></label>`}
function poster(v){return v.poster_url||''}
function card(v){const id=v.id,title=v.title||'Untitled',year=v.release_date?.slice(0,4)||v.year||'—',p=poster(v);return `<article class="movie-card" data-id="${esc(id)}"><div class="movie-poster">${p?`<img src="${esc(p)}" alt="${esc(title)}" loading="lazy">`:'<span style="color:#fff;display:grid;place-items:center;height:100%;font-weight:900">NO POSTER</span>'}<span class="movie-type">TMDB</span></div><div class="movie-card-body"><h3>${esc(title)}</h3><div class="movie-meta">${esc(year)}</div>${v.vote_average?`<span class="movie-score">★ ${esc(Number(v.vote_average).toFixed(1))}/10</span>`:''}</div></article>`}
function bind(){document.querySelectorAll('.movie-card').forEach(c=>c.onclick=()=>location.href='movie-detail.html?id='+encodeURIComponent(c.dataset.id))}
async function loadMovies(){const grid=$('#movieGrid'),q=$('#movieSearchInput')?.value.trim()||'',sort=$('.movie-tab.active')?.dataset.sort||'popularity.desc';grid.innerHTML='<div class="movie-empty">Loading TMDB movie catalogue…</div>';const data=q?await api('/api/tmdb-movies?q='+encodeURIComponent(q)):await api('/api/tmdb-movies?sort='+encodeURIComponent(sort));const items=data?.results||[];if(!items.length){grid.innerHTML='<div class="movie-empty"><strong>No movies found.</strong><br>Try another title.</div>';return}grid.innerHTML=items.map(card).join('');bind()}
function setup(){initNav();const hero=document.querySelector('.movies-hero .container');if(hero&&!hero.querySelector('.movieRegion')){const wrap=document.createElement('div');wrap.className='region-wrap';wrap.innerHTML=regionControl();hero.appendChild(wrap)}document.querySelectorAll('.movieRegion').forEach(s=>s.addEventListener('change',e=>setRegion(e.target.value)));document.querySelectorAll('.movie-tab').forEach(t=>t.addEventListener('click',()=>{document.querySelectorAll('.movie-tab').forEach(x=>x.classList.remove('active'));t.classList.add('active');loadMovies()}));$('#movieSearchForm')?.addEventListener('submit',e=>{e.preventDefault();loadMovies()});loadMovies()}
function trailerId(v){return String(v||'').trim()}
async function loadDetail(){initNav();const id=new URLSearchParams(location.search).get('id'),root=$('#movieDetail');if(!id){root.innerHTML='<div class="movie-empty">No movie selected.</div>';return}const d=await api('/api/tmdb-movies/'+encodeURIComponent(id));if(!d||d.error){root.innerHTML='<div class="movie-empty">TMDB movie details are unavailable right now.</div>';return}const title=d.title||'Movie';document.title=title+' — Movie Centre';const trailer=d.trailer;root.innerHTML=`<div class="movie-detail-layout"><div class="movie-detail-poster">${d.poster_large||d.poster_url?`<img src="${esc(d.poster_large||d.poster_url)}" alt="${esc(title)}">`:''}</div><div class="movie-detail"><span class="eyebrow">TMDB MOVIE CENTRE</span><h1>${esc(title)}</h1><div class="meta">${esc(d.release_date||'')} ${d.runtime?`· ${esc(d.runtime)} min`:''} ${d.vote_average?`· ★ ${esc(Number(d.vote_average).toFixed(1))}/10`:''}</div><p class="overview">${esc(d.overview||'No overview is available for this title yet.')}</p><div class="movie-actions">${trailer?`<button class="movie-action" id="watchTrailer">▶ Watch trailer</button>`:''}<a class="movie-action secondary" href="movies.html">← Back to movies</a></div></div></div><div class="availability"><div class="availability-head"><h2>Where to watch</h2>${regionControl()}</div><div id="sourceList" class="source-list"><div class="movie-empty">Checking availability…</div></div><p class="watchmode-note">Provider availability comes from TMDB's JustWatch-powered data. It identifies legal services; it does not provide the movie file for playback.</p></div>${d.cast?.length?`<div class="availability"><h2>Cast</h2><p class="cast-hint">Select an artist to view their profile, biography and other movies.</p><div class="cast-grid">${d.cast.map(c=>`<a class="cast-card cast-link" href="artist-detail.html?id=${encodeURIComponent(c.id||'')}">${c.headshot_url?`<img src="${esc(c.headshot_url)}" alt="${esc(c.name||'Cast member')}" loading="lazy">`:''}<div><strong>${esc(c.name||'Unknown')}</strong><br>${esc(c.character||'')}</div></a>`).join('')}</div></div>`:''}${trailer?`<div class="availability"><h2>Trailer</h2><div class="trailer-box"><iframe src="https://www.youtube-nocookie.com/embed/${encodeURIComponent(trailerId(trailer))}" title="${esc(title)} trailer" allow="accelerometer; autoplay; encrypted-media; picture-in-picture" allowfullscreen></iframe></div></div>`:''}`;document.querySelectorAll('#movieDetail .movieRegion').forEach(s=>s.addEventListener('change',e=>refreshProviders(id,e.target.value)));await refreshProviders(id,getRegion());$('#watchTrailer')?.addEventListener('click',()=>document.querySelector('.trailer-box')?.scrollIntoView({behavior:'smooth'}))}
async function refreshProviders(id,region){const box=$('#sourceList');if(!box)return;box.innerHTML='<div class="movie-empty">Checking '+esc(region)+' availability…</div>';const d=await api('/api/tmdb-movies/'+encodeURIComponent(id)+'/providers?region='+encodeURIComponent(region));const groups=[['Streaming',d?.flatrate],['Free',d?.free],['With ads',d?.ads],['Rent',d?.rent],['Buy',d?.buy]];const cards=[];groups.forEach(([label,list])=>(list||[]).forEach(p=>cards.push(`<div class="source-card"><strong>${esc(p.provider_name||'Provider')}</strong><small>${esc(label)}</small></div>`)));if(d?.link)cards.push(`<div class="source-card"><strong>TMDB / JustWatch</strong><small>Full availability</small><a href="${esc(d.link)}" target="_blank" rel="noopener noreferrer">View legal options →</a></div>`);box.innerHTML=cards.length?cards.join(''):'<div class="movie-empty"><strong>No provider was listed for this country.</strong><br>Try another country.</div>'}
document.addEventListener('DOMContentLoaded',()=>{if($('#movieGrid'))setup();if($('#movieDetail'))loadDetail()});