document.documentElement.classList.add('js');
window.APP_CONFIG=window.APP_CONFIG||{API_BASE_URL:'https://fabrizio-romanio-backend.onrender.com',AUTO_REFRESH_MS:60000,ENDPOINTS:{news:'/api/youtube-videos',transfers:'/api/transfers',videos:'/api/youtube-videos',players:'/api/players',clubs:'/api/clubs',settings:'/api/settings'}};
window.apiFetch=async function(endpoint,fallback=null,options={}){const base=String(window.APP_CONFIG.API_BASE_URL||'').replace(/\/$/,'');if(!base)return fallback;try{const r=await fetch(base+endpoint,{headers:{Accept:'application/json'},...options});if(!r.ok)throw new Error('API '+r.status);return await r.json()}catch(e){console.warn('Backend request failed:',endpoint,e.message);return fallback}};
function hidePageLoader(){document.querySelector('.page-loader')?.classList.add('hidden');document.body.classList.remove('loading')}
function initNavigation(){const b=document.querySelector('.menu-btn'),n=document.querySelector('.nav-links');if(!b||!n)return;b.addEventListener('click',()=>{const o=n.classList.toggle('mobile-open');b.setAttribute('aria-expanded',String(o))});n.querySelectorAll('a').forEach(a=>a.addEventListener('click',()=>{n.classList.remove('mobile-open');b.setAttribute('aria-expanded','false')}))}
function applyTheme(t){document.documentElement.dataset.theme=t;document.documentElement.style.colorScheme=t==='dark'?'dark':t==='light'?'light':'normal'}
function initSettings(){const inputs=document.querySelectorAll('input[name="theme"]'),saved=localStorage.getItem('fr-theme')||'system';inputs.forEach(i=>{i.checked=i.value===saved;i.addEventListener('change',()=>{localStorage.setItem('fr-theme',i.value);applyTheme(i.value)})});const a=document.getElementById('autoRefresh');if(a){a.checked=localStorage.getItem('fr-auto-refresh')!=='off';a.addEventListener('change',()=>localStorage.setItem('fr-auto-refresh',a.checked?'on':'off'))}document.getElementById('resetSettings')?.addEventListener('click',()=>{localStorage.removeItem('fr-theme');localStorage.removeItem('fr-auto-refresh');location.reload()});applyTheme(saved)}
function initSearch(){document.querySelector('.search-btn')?.addEventListener('click',()=>{const q=prompt('Search football news, players or clubs:');if(q?.trim())location.href='news.html?q='+encodeURIComponent(q.trim())})}
function formatDate(value){if(!value)return 'Recently';const d=new Date(value);if(Number.isNaN(d.getTime()))return 'Recently';return new Intl.DateTimeFormat(undefined,{day:'numeric',month:'short',year:'numeric'}).format(d)}
function cleanText(value){return String(value??'').replace(/[&<>\"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',"'":'&#39;'}[c]))}
function normalizeVideos(payload){if(Array.isArray(payload))return payload;if(Array.isArray(payload?.videos))return payload.videos;if(Array.isArray(payload?.data))return payload.data;return []}
function getThumb(v){return v.thumbnails?.high||v.thumbnails?.medium||v.thumbnails?.default||''}
function getVideoId(v){return v.video_id||String(v.url||'').match(/[?&]v=([^&]+)/)?.[1]||''}
function getUrl(v){return v.url||('https://www.youtube.com/watch?v='+getVideoId(v))}
function openVideoPlayer(v){const id=getVideoId(v);if(!id)return;const title=cleanText(v.title||'Football video');let modal=document.getElementById('videoPlayerModal');if(!modal){modal=document.createElement('div');modal.id='videoPlayerModal';modal.className='video-modal';modal.innerHTML='<div class="video-modal-backdrop" data-close-video></div><div class="video-modal-dialog" role="dialog" aria-modal="true" aria-label="Video player"><button class="video-modal-close" type="button" data-close-video aria-label="Close video">×</button><div class="video-frame"><iframe id="videoPlayerFrame" title="Football video" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowfullscreen></iframe></div><div class="video-modal-info"><span class="tag red">WATCH ON OUR WEBSITE</span><h2 id="videoPlayerTitle"></h2></div></div>';document.body.appendChild(modal);modal.querySelectorAll('[data-close-video]').forEach(el=>el.addEventListener('click',closeVideoPlayer))}modal.querySelector('#videoPlayerTitle').textContent=title;modal.querySelector('#videoPlayerFrame').src='https://www.youtube-nocookie.com/embed/'+encodeURIComponent(id)+'?autoplay=1&rel=0';modal.classList.add('open');document.body.classList.add('video-open')}
function closeVideoPlayer(){const modal=document.getElementById('videoPlayerModal');if(!modal)return;modal.classList.remove('open');document.body.classList.remove('video-open');const frame=modal.querySelector('#videoPlayerFrame');if(frame)frame.src=''}
function videoCard(v){const title=cleanText(v.title||'Football transfer news update'),channel=cleanText(v.channel_title||'YouTube'),date=formatDate(v.published_at),thumb=getThumb(v);return `<article class="video-card api-video-card" tabindex="0" role="button" data-video-id="${cleanText(getVideoId(v))}"><div class="video-thumb" style="${thumb?`background-image:url('${cleanText(thumb)}');background-size:cover;background-position:center`:''}"><span class="play-overlay">▶</span></div><h3>${title}</h3><small>${channel} · ${date}</small></article>`}
function newsCard(v){const title=cleanText(v.title||'Football news update'),channel=cleanText(v.channel_title||'YouTube'),date=formatDate(v.published_at),thumb=getThumb(v);return `<article class="news-card api-news-card" tabindex="0" role="button" data-video-id="${cleanText(getVideoId(v))}"><div class="news-img" style="${thumb?`background-image:url('${cleanText(thumb)}');background-size:cover;background-position:center`:''}"><span class="play-overlay">▶</span></div><span class="tag red">FOOTBALL REPORT</span><h3>${title}</h3><small>${channel} · ${date}</small></article>`}
function bindVideoCards(){document.querySelectorAll('[data-video-id]').forEach(card=>{if(card.dataset.bound)return;card.dataset.bound='1';const play=()=>{const id=card.dataset.videoId;if(id)openVideoPlayer({video_id:id,title:card.querySelector('h3')?.textContent||'Football video'})};card.addEventListener('click',play);card.addEventListener('keydown',e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();play()}})})}
async function loadVideos(){const grids=document.querySelectorAll('.video-grid[data-api="youtube"]');if(!grids.length)return;const videos=normalizeVideos(await window.apiFetch('/api/youtube-videos?limit=24',null));if(!videos.length)return;grids.forEach(grid=>grid.innerHTML=videos.map(videoCard).join(''));bindVideoCards()}
async function loadNews(){const grids=document.querySelectorAll('.news-grid[data-api="youtube-news"]');if(!grids.length)return;const videos=normalizeVideos(await window.apiFetch('/api/youtube-videos?limit=24',null));if(!videos.length)return;grids.forEach(grid=>grid.innerHTML=videos.map(newsCard).join(''));bindVideoCards()}
async function loadFeaturedVideo(){const feature=document.querySelector('[data-api="youtube-feature"]');if(!feature)return;const videos=normalizeVideos(await window.apiFetch('/api/youtube-videos?limit=1',null));const v=videos[0];if(!v)return;const title=cleanText(v.title||'Latest football news'),thumb=getThumb(v),id=cleanText(getVideoId(v));feature.innerHTML=`<div class="api-feature-content" data-video-id="${id}" tabindex="0" role="button"><div class="feature-media video-thumb" style="${thumb?`background-image:url('${cleanText(thumb)}');background-size:cover;background-position:center`:''}"><span class="play-overlay">▶</span></div><div class="feature-copy"><span class="tag red">WATCH ON OUR WEBSITE</span><h2>${title}</h2><span class="muted">${formatDate(v.published_at)} · ${cleanText(v.channel_title||'YouTube')}</span></div></div>`;bindVideoCards()}
async function loadApiContent(){await Promise.all([loadVideos(),loadNews(),loadFeaturedVideo()])}
document.addEventListener('DOMContentLoaded',()=>{document.body.classList.add('loading');initNavigation();initSettings();initSearch();loadApiContent();window.addEventListener('load',()=>setTimeout(hidePageLoader,450),{once:true});setTimeout(hidePageLoader,2500)});