document.documentElement.classList.add('js');
window.APP_CONFIG=window.APP_CONFIG||{API_BASE_URL:'https://fabrizio-romanio-backend.onrender.com',AUTO_REFRESH_MS:60000,ENDPOINTS:{news:'/api/youtube-videos',transfers:'/api/youtube-videos',videos:'/api/youtube-videos',players:'/api/players',clubs:'/api/clubs',settings:'/api/settings'}};
window.apiFetch=async function(endpoint,fallback=null,options={}){const base=String(window.APP_CONFIG.API_BASE_URL||'').replace(/\/$/,'');if(!base)return fallback;try{const r=await fetch(base+endpoint,{headers:{Accept:'application/json'},...options});if(!r.ok)throw new Error('API '+r.status);return await r.json()}catch(e){console.warn('Backend request failed:',endpoint,e.message);return fallback}};
function hidePageLoader(){document.querySelector('.page-loader')?.classList.add('hidden');document.body.classList.remove('loading')}
function initNavigation(){const b=document.querySelector('.menu-btn'),n=document.querySelector('.nav-links');if(!b||!n)return;b.addEventListener('click',()=>{const o=n.classList.toggle('mobile-open');b.setAttribute('aria-expanded',String(o))});n.querySelectorAll('a').forEach(a=>a.addEventListener('click',()=>{n.classList.remove('mobile-open');b.setAttribute('aria-expanded','false')}))}
function applyTheme(t){document.documentElement.dataset.theme=t;document.documentElement.style.colorScheme=t==='dark'?'dark':t==='light'?'light':'normal'}
function initSettings(){const inputs=document.querySelectorAll('input[name="theme"]'),saved=localStorage.getItem('fr-theme')||'system';inputs.forEach(i=>{i.checked=i.value===saved;i.addEventListener('change',()=>{localStorage.setItem('fr-theme',i.value);applyTheme(i.value)})});const a=document.getElementById('autoRefresh');if(a){a.checked=localStorage.getItem('fr-auto-refresh')!=='off';a.addEventListener('change',()=>localStorage.setItem('fr-auto-refresh',a.checked?'on':'off'))}document.getElementById('resetSettings')?.addEventListener('click',()=>{localStorage.removeItem('fr-theme');localStorage.removeItem('fr-auto-refresh');location.reload()});applyTheme(saved)}
function initSearch(){const button=document.querySelector('.search-btn');if(!button)return;button.addEventListener('click',()=>{let modal=document.getElementById('siteSearchModal');if(!modal){modal=document.createElement('div');modal.id='siteSearchModal';modal.className='search-modal';modal.innerHTML='<div class="search-modal-backdrop" data-close-search></div><div class="search-modal-dialog" role="dialog" aria-modal="true" aria-label="Search football news"><button class="search-modal-close" type="button" data-close-search aria-label="Close search">×</button><span class="eyebrow">SEARCH THE NEWSROOM</span><h2>Find football news</h2><form id="siteSearchForm"><div class="search-input-wrap"><span>⌕</span><input id="siteSearchInput" type="search" placeholder="Search players, clubs, transfers..." autocomplete="off"><button type="submit">Search</button></div></form><p>Search the connected football video news feed and watch results directly on this website.</p></div>';document.body.appendChild(modal);modal.querySelectorAll('[data-close-search]').forEach(el=>el.addEventListener('click',()=>modal.classList.remove('open')));modal.querySelector('#siteSearchForm').addEventListener('submit',e=>{e.preventDefault();const q=modal.querySelector('#siteSearchInput').value.trim();if(q)location.href='news.html?q='+encodeURIComponent(q)});}modal.classList.add('open');setTimeout(()=>modal.querySelector('#siteSearchInput')?.focus(),50)})}
function formatDate(value){if(!value)return 'Recently';const d=new Date(value);if(Number.isNaN(d.getTime()))return 'Recently';return new Intl.DateTimeFormat(undefined,{day:'numeric',month:'short',year:'numeric'}).format(d)}
function cleanText(value){return String(value??'').replace(/[&<>\"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',"'":'&#39;'}[c]))}
function normalizeVideos(payload){if(Array.isArray(payload))return payload;if(Array.isArray(payload?.videos))return payload.videos;if(Array.isArray(payload?.data))return payload.data;return []}
function getThumb(v){const t=v?.thumbnails||{};return t.maxres?.url||t.standard?.url||t.high?.url||t.medium?.url||t.default?.url||t.maxres||t.standard||t.high||t.medium||t.default||''}
function getVideoId(v){return v.video_id||v.id||String(v.url||'').match(/[?&]v=([^&]+)/)?.[1]||''}
function imageMarkup(v,className){const thumb=cleanText(getThumb(v));return `<div class="${className}">${thumb?`<img src="${thumb}" alt="${cleanText(v.title||'Football news')}" loading="lazy" referrerpolicy="no-referrer" onerror="this.style.display='none';this.parentElement.classList.add('image-failed')">`:'<span class="image-placeholder">FOOTBALL</span>'}<span class="play-overlay">▶</span></div>`}
function openVideoPlayer(v){const id=getVideoId(v);if(!id)return;const title=cleanText(v.title||'Football video');let modal=document.getElementById('videoPlayerModal');if(!modal){modal=document.createElement('div');modal.id='videoPlayerModal';modal.className='video-modal';modal.innerHTML='<div class="video-modal-backdrop" data-close-video></div><div class="video-modal-dialog" role="dialog" aria-modal="true" aria-label="Video player"><button class="video-modal-close" type="button" data-close-video aria-label="Close video">×</button><div class="video-frame"><iframe id="videoPlayerFrame" title="Football video" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowfullscreen></iframe></div><div class="video-modal-info"><span class="tag red">WATCH ON OUR WEBSITE</span><h2 id="videoPlayerTitle"></h2></div></div>';document.body.appendChild(modal);modal.querySelectorAll('[data-close-video]').forEach(el=>el.addEventListener('click',closeVideoPlayer))}modal.querySelector('#videoPlayerTitle').textContent=title;modal.querySelector('#videoPlayerFrame').src='https://www.youtube-nocookie.com/embed/'+encodeURIComponent(id)+'?autoplay=1&rel=0';modal.classList.add('open');document.body.classList.add('video-open')}
function closeVideoPlayer(){const modal=document.getElementById('videoPlayerModal');if(!modal)return;modal.classList.remove('open');document.body.classList.remove('video-open');const frame=modal.querySelector('#videoPlayerFrame');if(frame)frame.src=''}
function videoCard(v){const title=cleanText(v.title||'Football transfer news update'),channel=cleanText(v.channel_title||'YouTube'),date=formatDate(v.published_at);return `<article class="video-card api-video-card" tabindex="0" role="button" data-video-id="${cleanText(getVideoId(v))}">${imageMarkup(v,'video-thumb')}<h3>${title}</h3><small>${channel} · ${date}</small></article>`}
function newsCard(v){const title=cleanText(v.title||'Football news update'),channel=cleanText(v.channel_title||'YouTube'),date=formatDate(v.published_at);return `<article class="news-card api-news-card" tabindex="0" role="button" data-video-id="${cleanText(getVideoId(v))}">${imageMarkup(v,'news-img')}<span class="tag red">FOOTBALL REPORT</span><h3>${title}</h3><small>${channel} · ${date}</small></article>`}
function transferCard(v){const title=cleanText(v.title||'Latest transfer report'),channel=cleanText(v.channel_title||'YouTube'),date=formatDate(v.published_at),id=cleanText(getVideoId(v));return `<article class="transfer-feature-card" data-video-id="${id}" tabindex="0" role="button"><div class="transfer-image">${imageMarkup(v,'transfer-thumb')}</div><div class="transfer-copy"><span class="tag red">LIVE TRANSFER REPORT</span><h2>${title}</h2><p class="transfer-meta">${channel} · ${date}</p><p class="transfer-summary">Latest transfer-market report from the connected football video feed.</p><a class="transfer-detail-link" href="features-detail.html?id=${encodeURIComponent(id)}" onclick="event.stopPropagation()">Read full feature →</a></div></article>`}
function bindVideoCards(){document.querySelectorAll('[data-video-id]').forEach(card=>{if(card.dataset.bound)return;card.dataset.bound='1';const play=()=>{const id=card.dataset.videoId;if(id)openVideoPlayer({video_id:id,title:card.querySelector('h3,h2')?.textContent||'Football video'})};card.addEventListener('click',e=>{if(e.target.closest('a'))return;play()});card.addEventListener('keydown',e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();play()}})})}
function getSearchQuery(){return new URLSearchParams(location.search).get('q')?.trim()||''}
async function loadVideos(){const grids=document.querySelectorAll('.video-grid[data-api="youtube"]');if(!grids.length)return;const videos=normalizeVideos(await window.apiFetch('/api/youtube-videos?limit=24',null));if(!videos.length)return;grids.forEach(grid=>grid.innerHTML=videos.map(videoCard).join(''));bindVideoCards()}
async function loadNews(){const grids=document.querySelectorAll('.news-grid[data-api="youtube-news"]');if(!grids.length)return;const q=getSearchQuery();const endpoint='/api/youtube-videos?limit=24'+(q?'&q='+encodeURIComponent(q):'');const videos=normalizeVideos(await window.apiFetch(endpoint,null));if(!videos.length){grids.forEach(grid=>grid.innerHTML='<div class="empty-state"><h3>No football stories found</h3><p>Try another player, club, league or transfer search.</p></div>');return}grids.forEach(grid=>grid.innerHTML=videos.map(newsCard).join(''));const heading=document.querySelector('.newsroom-query');if(heading)heading.textContent=q?'Search results for “'+q+'”':'Latest football stories';bindVideoCards()}
async function loadFeaturedVideo(){const feature=document.querySelector('[data-api="youtube-feature"]');if(!feature)return;const videos=normalizeVideos(await window.apiFetch('/api/youtube-videos?limit=1',null));const v=videos[0];if(!v)return;const title=cleanText(v.title||'Latest football news'),id=cleanText(getVideoId(v));feature.innerHTML=`<div class="api-feature-content" data-video-id="${id}" tabindex="0" role="button">${imageMarkup(v,'feature-media video-thumb')}<div class="feature-copy"><span class="tag red">WATCH ON OUR WEBSITE</span><h2>${title}</h2><span class="muted">${formatDate(v.published_at)} · ${cleanText(v.channel_title||'YouTube')}</span></div></div>`;bindVideoCards()}
async function loadTransferNews(force=false){const grid=document.querySelector('[data-api="youtube-transfers"]');if(!grid)return;grid.classList.add('is-loading');const endpoint='/api/youtube-videos?limit=24&q='+encodeURIComponent('football transfer news')+(force?'&t='+Date.now():'');const videos=normalizeVideos(await window.apiFetch(endpoint,null));if(videos.length)grid.innerHTML=videos.map(transferCard).join('');else grid.innerHTML='<div class="empty-state"><h3>No transfer reports found</h3><p>Please try again shortly.</p></div>';grid.classList.remove('is-loading');bindVideoCards()}
async function loadFeatureDetail(){const root=document.querySelector('[data-feature-detail]');if(!root)return;const id=new URLSearchParams(location.search).get('id');if(!id){root.innerHTML='<div class="empty-state">This feature could not be found.</div>';return}const videos=normalizeVideos(await window.apiFetch('/api/youtube-videos?limit=50&q='+encodeURIComponent('football transfer news'),null));const v=videos.find(item=>getVideoId(item)===id);if(!v){root.innerHTML='<div class="empty-state"><h3>Feature not found</h3><p>The live video may have moved out of the current feed. Return to the Transfer Centre for the latest stories.</p></div>';return}const title=cleanText(v.title||'Transfer feature');root.innerHTML=`<div class="detail-media">${imageMarkup(v,'detail-image')}<button class="detail-play" type="button">▶ Watch report</button></div><div class="detail-body"><span class="eyebrow">TRANSFER FEATURE</span><h1>${title}</h1><p class="detail-meta">${cleanText(v.channel_title||'YouTube')} · ${formatDate(v.published_at)}</p><div class="detail-description"><p>${cleanText(v.description||'This feature contains the latest available transfer-market report from the connected football feed.')}</p></div><button class="detail-watch" type="button">▶ Watch report on our website</button></div>`;root.querySelectorAll('.detail-play,.detail-watch').forEach(b=>b.addEventListener('click',()=>openVideoPlayer(v)))}
async function loadApiContent(){await Promise.all([loadVideos(),loadNews(),loadFeaturedVideo(),loadTransferNews(),loadFeatureDetail()])}
document.addEventListener('DOMContentLoaded',()=>{document.body.classList.add('loading');initNavigation();initSettings();initSearch();loadApiContent();window.addEventListener('load',()=>setTimeout(hidePageLoader,450),{once:true});setTimeout(hidePageLoader,2500)});