const TMDB_LIST_API='https://fabrizio-romanio-backend.onrender.com';
const tmdbListEsc=v=>String(v??'').replace(/[&<>\"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',"'":'&#39;'}[c]));
async function tmdbListApi(path,options={}){const r=await fetch(TMDB_LIST_API+path,{credentials:'include',headers:{Accept:'application/json','Content-Type':'application/json'},...options});const d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d.message||d.error||`Request failed (${r.status})`);return d}
async function tmdbListStatus(){return tmdbListApi('/api/tmdb-auth/status')}
function tmdbConnect(){tmdbListApi('/api/tmdb-auth/start',{method:'POST',body:JSON.stringify({redirect_to:location.origin+'/lists.html'})}).then(d=>{if(d.approval_url)location.href=d.approval_url}).catch(e=>alert(e.message))}
async function tmdbLogout(){await tmdbListApi('/api/tmdb-auth/logout',{method:'POST'});location.reload()}
async function loadTmdbLists(){return tmdbListApi('/api/tmdb-user/lists')}
async function createTmdbList(name,description,isPublic=false){return tmdbListApi('/api/tmdb-user/lists',{method:'POST',body:JSON.stringify({name,description,public:isPublic})})}
async function addTmdbMovieToList(listId,movieId){return tmdbListApi(`/api/tmdb-user/lists/${encodeURIComponent(listId)}/items`,{method:'POST',body:JSON.stringify({media_type:'movie',media_id:Number(movieId)})})}
window.TMDBLists={api:tmdbListApi,status:tmdbListStatus,connect:tmdbConnect,logout:tmdbLogout,load:loadTmdbLists,create:createTmdbList,addMovie:addTmdbMovieToList};
async function renderListsPage(){const root=document.getElementById('listsRoot');if(!root)return;root.innerHTML='<div class="lists-loading">Checking your TMDB connection…</div>';try{const status=await tmdbListStatus();if(!status.connected){root.innerHTML='<div class="lists-connect"><span class="eyebrow">TMDB ACCOUNT</span><h2>Connect your TMDB account</h2><p>Connect securely through TMDB to create lists and save movies. Your TMDB access token stays in an HttpOnly backend cookie.</p><button class="lists-btn" id="connectTmdb">Connect TMDB →</button></div>';document.getElementById('connectTmdb').onclick=tmdbConnect;return}renderConnectedLists(root)}catch(e){root.innerHTML=`<div class="lists-error">${tmdbListEsc(e.message)}</div>`}}
async function renderConnectedLists(root){root.innerHTML='<div class="lists-loading">Loading your lists…</div>';try{const d=await loadTmdbLists();const lists=d.results||[];root.innerHTML=`<div class="lists-toolbar"><div><span class="eyebrow">CONNECTED TO TMDB</span><h2>Your Movie Lists</h2><p>Create lists on TMDB and save movies from our Movie Centre.</p></div><button class="lists-btn secondary" id="logoutTmdb">Disconnect</button></div><form id="createListForm" class="create-list"><input id="listName" required maxlength="100" placeholder="List name, e.g. Weekend Watchlist"><input id="listDescription" maxlength="300" placeholder="Description (optional)"><label><input id="listPublic" type="checkbox"> Public</label><button class="lists-btn" type="submit">Create list</button></form><div class="lists-grid">${lists.length?lists.map(list=>`<a class="list-card" href="list-detail.html?id=${encodeURIComponent(list.id)}"><div class="list-poster">${list.backdrop_path?`<img src="https://image.tmdb.org/t/p/w780${tmdbListEsc(list.backdrop_path)}" alt="">`:'🎬'}</div><div class="list-copy"><strong>${tmdbListEsc(list.name||'Untitled list')}</strong><small>${Number(list.number_of_items||0)} items · ${list.public?'Public':'Private'}</small></div></a>`).join(''):'<div class="lists-empty">You have no lists yet. Create your first one above.</div>'}</div>`;document.getElementById('logoutTmdb').onclick=tmdbLogout;document.getElementById('createListForm').onsubmit=async e=>{e.preventDefault();const b=e.currentTarget.querySelector('button');b.disabled=true;try{await createTmdbList(document.getElementById('listName').value,document.getElementById('listDescription').value,document.getElementById('listPublic').checked);await renderConnectedLists(root)}catch(err){alert(err.message)}finally{b.disabled=false}}}catch(e){root.innerHTML=`<div class="lists-error">${tmdbListEsc(e.message)}</div>`}}
document.addEventListener('DOMContentLoaded',()=>{if(document.getElementById('listsRoot'))renderListsPage()});
